### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by Vinayak-VG** [pp00704831/Stripformer-ECCV-2022-#10]
could you please tell me how long it takes to complete the stage I and stage II training on the NVIDIA 3090 GPU?

**Comment by pp00704831** [comment]
Hello,

I use 8 NVIDIA 3090 GPUs to train, and I don't remember the time it needed to train, maybe at least one week.
You can also use 2000 epochs to train on 256x256 patches and then tune it for 1000 epochs on 512x512 patches to save time.
