### ISSUE TITLE
GMACs with 256*256*3 input

### ISSUE THREAD

**Issue by joshyZhou** [pp00704831/Stripformer-ECCV-2022-#12]
Hi,
Thanks for your great work! We note that the FLOPS is reported with the same setting as IPT. Indeed, we guess the result has come from the 48*48 input. Can you share the GMACs with the 256*256*3 input, where we would like to make a comparison.

**Comment by pp00704831** [comment]
Hi,

I report the GFLOPs from the 256x256x3 inputs in #6, is it suitable for you to make a comparison?

**Comment by joshyZhou** [comment]
> 

Thanks so much for your quick reply, and this is enough for us to make the comparison!
