### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by Ideal-Bushgorman** [pp00704831/Stripformer-ECCV-2022-#13]
Hi！ Your work was so interesting and it was attractive to me. I want to know what type of GPU is needed for training, as well as the number of GPUs and training time.

**Comment by pp00704831** [comment]
Hi,

Thank you for your interest. I use eight 3090 GPUs to train and one 3090 GPU to test.
I don't remember the exact training time, but it might take one week to train.

**Comment by Ideal-Bushgorman** [comment]
thank you very much
