### ISSUE TITLE
關於訓練細節的問題

### ISSUE THREAD

**Issue by hubzyx** [pp00704831/Stripformer-ECCV-2022-#15]
您好，我對這項研究十分感興趣，不過我在復現的時候存在一些問題，希望您能抽出一些時間幫忙解答一下。
我在論文裏並沒有看到很多的訓練細節，不過我在代碼中看到了您在256x256尺寸的圖像使用batchsize=8預訓練3000輪後，使用512x512尺寸的圖像batchsize=8再訓練1000輪，想請問您在論文中的結果也是使用同樣的方法嗎？
以及想了解您具體用了幾張什麽型號的顯卡用於訓練呢？

**Comment by pp00704831** [comment]
您好，

我在訓練時先使用 256x256 的圖像搭配 batchsize=8 訓練 3000 epochs，之後再使用 512x512 訓練 1000 epochs，論文中的結果也是使用相同方法。我一共使用8張3090進行訓練，最後使用一張3090測試。
