### ISSUE TITLE
关于对比损失的问题

### ISSUE THREAD

**Issue by ifei17-hfut** [pp00704831/Stripformer-ECCV-2022-#16]
您好，请问您在使用对比损失去约束restore, sharp, blur之间的距离时，正样本和负样本的数量都是一一对应的吗？

**Comment by pp00704831** [comment]
謝謝你的關注。沒錯，我是使用一一對應的正樣本和負樣本數量。

**Comment by ifei17-hfut** [comment]
好嘞谢谢您！您的工作非常有帮助，我在阅读了您的论文时看到您的实验表格中：有负样本为10，正样本为1的对比损失的验证实验。我想请教您，对于一个样本（负样本），如何使得他在一个batch中表示为十种负样本？

**Comment by pp00704831** [comment]
我的表格應該沒有負樣本為10的例子，也許你是看到別人的論文?
至於十種負樣本，也許可以拿同一個batch內別張模糊圖像，但這會有內容不一致的問題，效果不見得會好。

**Comment by ifei17-hfut** [comment]
不好意思确实记错了，非常感谢您的帮助！
