### ISSUE TITLE
Question about Continue Training with 512*512

### ISSUE THREAD

**Issue by HanzhouLiu** [pp00704831/Stripformer-ECCV-2022-#17]
Thanks for your amazing work! I have one question about continue training with 512*512. I noticed that you didn't load the optimizer state when continue training with a patch size of 512*512.  Is there a reason why the old optimizer states are not needed? I also noticed that when you resume training with the same patch size of 256*256, you loaded the old optimizer states. Any answer or direction will be appreciated!

**Comment by pp00704831** [comment]
Hello,

Thank you for your interest.
It is better to use learning rates from 1e-4 to 1e-7 during the training stage with size 512*512.
Thus, I did not load the optimizer state used in the training stage with patch size 256*256.

**Comment by HanzhouLiu** [comment]
Thanks for your quick response! It makes sense!!
