### ISSUE TITLE
Noises in Deblurred Images During Training

### ISSUE THREAD

**Issue by HanzhouLiu** [pp00704831/Stripformer-ECCV-2022-#18]
I noticed that some deblurred images have red and green noises when I trained it myself. Continue training doesn't remove all the unpleasant noises. Here is the link to the picture ,
[noisy deblurred images](https://ibb.co/N1Rxg5P)
Also, I re-train other deblurring models based on your provided codes and had the same issue.
I am wondering what might cause this issue. Any hints will be appreciated. Thank you.

**Comment by pp00704831** [comment]
Hello, 

What kind of datasets do you use for training? 
During training, I did not find noisy artifacts when using GoPro or RealBlur datasets.
You can also check if you loaded the correct blurry and sharp pairs during training.

**Comment by HanzhouLiu** [comment]
I used GoPro for training. I am not sure if the issue comes from different versions of libraries. I will keep looking for the reason why colorful artifacts were introduced after training on my machine. The deblurring qualitative results were good if ignoring the annoying noises. So weird.

**Comment by HanzhouLiu** [comment]
The tensorboard showed me noisy deblurred images. I tested the model not on tensorboard and results are of good quality. I guess it is due to bad color correction or something like that by tensorboard. Just ignore tensorboard and everything else is good. Thanks for your work again.
