### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by Brightlcz** [pp00704831/Stripformer-ECCV-2022-#2]
Hello, @pp00704831   Congratulations on your paper being published on ECCV2022(oral):

I followed your readme, but the training result keeps getting an error, what is the problem?
error:
W0803 17:07:27.647219 34812 warnings.py:99] /home/amax/anaconda3/envs/Strip/lib/python3.6/site-packages/albumentations/imgaug/transforms.py:222: FutureWarning: IAASharpen is deprecated. Please use Sharpen instead
  warnings.warn("IAASharpen is deprecated. Please use Sharpen instead", FutureWarning)

W0803 17:07:27.647964 34812 warnings.py:99] /home/amax/anaconda3/envs/Strip/lib/python3.6/site-packages/albumentations/imgaug/transforms.py:165: FutureWarning: This augmentation is deprecated. Please use Emboss instead
  warnings.warn("This augmentation is deprecated. Please use Emboss instead", FutureWarning)

I0803 17:07:27.648266 34812 dataset.py:28] Subsampling buckets from 0 to 100, total buckets number is 100
Traceback (most recent call last):
  File "train_Stripformer_pretrained.py", line 162, in <module>
    train, val = map(get_dataloader, datasets)
  File "/mnt/Stripformer/dataset.py", line 132, in from_config
    files_a, files_b = map(list, zip(*data))
ValueError: not enough values to unpack (expected 2, got 0)
(Strip) amax@ict4-pc:/mnt/Stripformer$

**Comment by Brightlcz** [comment]
When I run the training command as sudo CUDA_VISIBLE_DEVICES=7 python train_Stripformer_pretrained.py, it returns this error:

  File "train_Stripformer_pretrained.py", line 23
    def __init__(self, config, train: DataLoader, val: DataLoader):
SyntaxError: invalid syntax

**Comment by pp00704831** [comment]
Hello, 

Do you put the training and test data in the right place?  For example: './datasets/GoPro/train/blur/**/*.png'
The training data path is similar to the test data path, you can run the test code first to make sure it.

Second, maybe you can try "pip install albumentations==1.1.0" to solve your problem.

**Comment by Brightlcz** [comment]
Thank you for your timely reply.
 I tried it and the testing process is normal, but the training still reports the same error......

**Comment by pp00704831** [comment]
I will check it as soon as possible.

**Comment by pp00704831** [comment]
Hello,

I retry the Installation and I can run successfully, you could check the installation in the readme or the training data place.
I guess the problem might come from the wrong place of training data.

**Comment by Brightlcz** [comment]
@pp00704831 Thanks for your help, the model is ready to train. The reason is that I put an extra space in the training path. Thank you for your excellent work. Unfortunately, I am not very familiar with the model, maybe I will continue to ask you technical questions.
