### ISSUE TITLE
Test Time

### ISSUE THREAD

**Issue by VOT-Gong** [pp00704831/Stripformer-ECCV-2022-#22]
Hello, I am very appreciated to your great work. As you mentioned in this paper, the inference time is 52 ms. But when I test the code, I found that the time is 2 s. Could you give me some help? Thanks for your advice.

**Comment by pp00704831** [comment]
Hello,

Sorry for the late reply. 
You can see this [issue](https://github.com/pp00704831/Stripformer-ECCV-2022-/issues/6) for more details.
