### ISSUE TITLE
Training Epochs on RealBlur-R

### ISSUE THREAD

**Issue by HanzhouLiu** [pp00704831/Stripformer-ECCV-2022-#23]
Thanks for your great work! I am wondering how many epoch you trained Stripformer on the RealBlur-R dataset.

**Comment by pp00704831** [comment]
Hello,

We follow previous deblurring works and finetune GoPro pre-trained Stripformer on the RealBlur-R dataset for 1000 epochs with 512x512 patches.

**Comment by HanzhouLiu** [comment]
Thanks!!
