### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [pp00704831/Stripformer-ECCV-2022-#3]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
https://github.com/PINTO0309/PINTO_model_zoo

Thank you.

**Comment by pp00704831** [comment]
I will update the license for Stripformer in recent days.

Thank you for your interest!

**Comment by pp00704831** [comment]
Hello,  I have updated the license.

**Comment by PINTO0309** [comment]
Thanks!
