### ISSUE TITLE
Log Files from Training

### ISSUE THREAD

**Issue by gauenk** [pp00704831/Stripformer-ECCV-2022-#4]
Thank you for your awesome code!

I am hoping you might open-source the log files you have from training. Maybe the training and validation loss as a function of epoch
(and/or batch) with an estimate of the runtime?

**Comment by pp00704831** [comment]
Hello,

I am sorry that I do not save the log files from training,  so I could not share this.

**Comment by gauenk** [comment]
Thank you for the info!
