### ISSUE TITLE
The error "NaN or Inf found in input tensor" occurred when the work get to 700 training epochs.

### ISSUE THREAD

**Issue by BingY998** [pp00704831/Stripformer-ECCV-2022-#5]
Hello, recently when I was training the network on the GTX 3090, batch_size=4 and all other Settings were left as default.The error "NaN or Inf found in input tensor" occurred when the work got to 700 training epochs.Could you give me some help?

**Comment by pp00704831** [comment]
Hello,

I use batch_size=8 during training.
if your device could not support batch_size=8, you could try the "gradient accumulation" strategy to train: https://kozodoi.me/python/deep%20learning/pytorch/tutorial/2021/02/19/gradient-accumulation.html
Please set the accum_iter=2 when using batch_size=4 during training.

**Comment by BingY998** [comment]
Ok, thank you！ I have read your paper, the training device is 3090, I think I can also use batch_size =8 on 3090, but CUDA out of memory error occurred. I'll use your method, thank you！
