### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by DDxk369** [pp00704831/Stripformer-ECCV-2022-#7]
Hello, when I tried to run this project, I got the following error, my data storage is according to the requirements of README.

C:\Users\asus\anaconda3\python.exe C:/Users/asus/PycharmProjects/Stripformer-main/Stripformer-main/train_Stripformer_pretrained.py
W1025 10:36:17.233240 64796 warnings.py:109] C:\Users\asus\anaconda3\lib\site-packages\albumentations\imgaug\transforms.py:233: FutureWarning: IAASharpen is deprecated. Please use Sharpen instead
  warnings.warn("IAASharpen is deprecated. Please use Sharpen instead", FutureWarning)

W1025 10:36:17.233240 64796 warnings.py:109] C:\Users\asus\anaconda3\lib\site-packages\albumentations\imgaug\transforms.py:176: FutureWarning: This augmentation is deprecated. Please use Emboss instead
  warnings.warn("This augmentation is deprecated. Please use Emboss instead", FutureWarning)

I1025 10:36:17.235235 64796 dataset.py:28] Subsampling buckets from 0 to 100, total buckets number is 100
I1025 10:36:17.235235 64796 dataset.py:71] Dataset has been created with 240 samples
Traceback (most recent call last):
  File "C:/Users/asus/PycharmProjects/Stripformer-main/Stripformer-main/train_Stripformer_pretrained.py", line 162, in <module>
    train, val = map(get_dataloader, datasets)
  File "C:\Users\asus\PycharmProjects\Stripformer-main\Stripformer-main\dataset.py", line 121, in from_config
    transform_fn = aug.get_transforms(size=config['size'], scope=config['scope'], crop=config['crop'])
  File "C:\Users\asus\PycharmProjects\Stripformer-main\Stripformer-main\aug.py", line 36, in get_transforms
    pipeline = albu.Compose([aug_fn, crop_fn], additional_targets={'target': 'image'})
  File "C:\Users\asus\anaconda3\lib\site-packages\albumentations\core\composition.py", line 170, in __init__
    self.add_targets(additional_targets)
  File "C:\Users\asus\anaconda3\lib\site-packages\albumentations\core\composition.py", line 115, in add_targets
    t.add_targets(additional_targets)
AttributeError: 'NoneType' object has no attribute 'add_targets'

**Comment by bingnan-baby** [comment]
Hi, I meet the same problem. How did you solve this error?

**Comment by pp00704831** [comment]
Hello,

It might come from the wrong file directory of the training set.
Please check whether you download the full training sets and put them in the right file directory.

**Comment by Calvin11311** [comment]
hi, when i tried change the val config "scope" from "None" to others ("geometric, weak") , this problem will disappear, so why setting "none scope" in "config_Stripformer_pretrained.yaml" has this problem ?
